apiVersion: v1
kind: ConfigMap
metadata:
  name: mypostgres-config

data:
  PGDATABASE: myappdb
  PGUSER: postgres
  PGHOST: mypostgres-clusterip
  #   PGDATABASE: postgres
  # PGUSER: postgres
  # PGHOST: mypostgres-clusterip