apiVersion: v1
kind: Service
metadata:
  name: myfrontend-node-port
  labels:
    component: frontend
    app: my-applb
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31110
  selector:
    component: frontend
    app: my-frontend