version: '3'

services: 
  myredis:
    image: 'redis:alpine'
  mypostgres:
    image: 'postgres:alpine'
    environment: 
      - POSTGRES_PASSWORD=P@ssw0rd123
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
  mynginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mynginx
    ports: 
      - '80:80'
    image: inql/music-library-mynginx
  mybackend:
    build: 
      dockerfile: Dockerfile.dev
      # dockerfile: Dockerfile.prod
      context: ./mybackend
    depends_on: 
      - 'mypostgres'
      - 'myredis'
      - 'mynginx'
    volumes:
      - /opt/app/node_modules 
      - ./mybackend:/opt/app
    environment: 
      - POSTGRES_HOST=mypostgres
      - POSTGRES_PASSWORD=P@ssw0rd123
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - REDIS_HOST=myredis
    ports:
      - "5000:5000"
    image: inql/music-library-mybackend
  myfrontend:
      build:
        dockerfile: Dockerfile.dev
        context: ./myfrontend
      depends_on: 
        - 'mynginx'
      volumes:
        - /opt/app/node_modules
        - ./myfrontend:/opt/app
      image: inql/music-library-myfrontend
