apiVersion: apps/v1
kind: Deployment
metadata:
  name: newbackend-deployment
  labels:
    component: backend
    name: my-app2

spec:
  template:
    metadata:
      name: newbackend-pod
      labels:
        component: backend
        name: my-app2
    spec:
      containers:
        - name: newbackend-container
          image: inql/mybackendlb2
          ports:
            - containerPort: 5000

  replicas: 3
  selector:
    matchLabels:
      name: my-app2
      component: backend